fix: devDependencies doesn't exist in rootPackageJson (#584)
i faced the following issue:

Cannot set properties of undefined (setting 'react')
/Users/imokhles/.nvm/versions/node/v20.13.1/lib/node_modules/create-react-native-library/lib/index.js:558
rootPackageJson.devDependencies.react =
examplePackageJson.dependencies.react;
                                          ^

TypeError: Cannot set properties of undefined (setting 'react')
at Object.create [as handler]
(/Users/imokhles/.nvm/versions/node/v20.13.1/lib/node_modules/create-react-native-library/lib/index.js:558:43)